module.exports = {
  prefix: 'tw-',
  purge: {
    mode: 'all',
    content: ['./src/**/*.js'],
  },
  darkMode: false,
  theme: {
    screens: {},
    inset: {
      0: 0,
      '1/2': '50%',
      full: '100%',
    },
    textColor: {
      black: '#000',
      white: '#fff',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
    },
    width: {
      0: 0,
      full: '100%',
    },
    height: {
      sm: '8px',
      md: '16px',
      lg: '24px',
      lgt: '32px',
      xl: '48px',
      xxl: '64px',
      full: '100%',
      screen: '100vh',
    },
    padding: {
      0: '0px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '48px',
      xxl: '64px',
    },
    borderColor: {
      transparent: 'transparent',
      fade: '#f0f0f0',
    },
    borderWidth: {
      0: '0px',
      1: '1px',
    },
    borderStyle: {
      solid: 'solid',
    },
    margin: {
      0: '0px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '48px',
      xxl: '64px',
    },
    fontSize: {
      md: '16px',
      lg: '18px',
      lgt: '20px',
      x: '22px',
      xxl: '24px',
      xxxl: '26px',
      '4xl': '28px',
      '5xl': '30px',
    },
    translate: {
      '1/2': '50%',
      '-1/2': '-50%',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: [
    'display',
    'flexDirection',
    'justifyContent',
    'alignItems',
    'width',
    'height',
    'padding',
    'borderColor',
    'borderStyle',
    'borderWidth',
    'margin',
    'fontSize',
    'fontWeight',
    'backgroundColor',
    'textColor',
    'textOpacity',
    'whitespace',
    'overflow',
    'minHeight',
    'position',
    'inset',
    'boxShadow',
    'zIndex',
    'transitionProperty',
    'transitionDuration',
    'transitionTimingFunction',
    'transitionDelay',
    'float',
    'clear',
    'textOverflow',
    'wordBreak',
    'textAlign',
    'translate',
    'transform',
  ],
};
